services:
  # Postgres Database
  postgres:
    image: postgres:16-alpine
    container_name: overseekv2-postgres-1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: overseek
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: overseekv2-elasticsearch-1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  # Redis (Queue & Cache)
  redis:
    image: redis:alpine
    container_name: overseekv2-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Node API (Express + Prisma)
  api:
    build:
      context: ./server
    container_name: overseekv2-api-1
    command: sh -c "npx prisma generate && npx ts-node src/index.ts"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/overseek
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: supersecretkey
      PORT: 3000
      REDIS_HOST: redis
    depends_on:
      - postgres
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow container to reach host
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
  server_node_modules:
